services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    expose:
      - "11434"
    volumes:
      - ollama_data:/app
    networks:
      - net
    command: >
      serve && pull mistral
  minio:
    image: minio/minio
    hostname: "minio"
    volumes:
      - ./minio:/minio_files
    environment:
      - MINIO_ACCESS_KEY=jean
      - MINIO_SECRET_KEY=jean-minio
    command: 'minio server /minio_files --console-address ":9001"'
    ports:
      - 9000:9000
      - 9001:9001
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    env_file:
      - .env
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 jean jean-minio;
      /usr/bin/mc mb --quiet myminio/test;
      /usr/bin/mc policy set none myminio/test;
      "
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python webcrm/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/Code
    ports:
      - "8000:8000"
    container_name: webcrm

  bot:
    build:
      context:  ./bot-api
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 5000
    volumes:
      - ./bot-api:/bot-api
    container_name: bot-api
    ports:
      - "5001:5000"
    depends_on:
        - web
