# Generated by Django 5.0.2 on 2024-02-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='company',
            field=models.CharField(default='NC', max_length=200),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='status',
            field=models.CharField(default='Pending', max_length=200),
        ),
    ]
