# Generated by Django 5.0.2 on 2024-02-19 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_image_url_alter_product_image'),
        ('sales', '0004_alter_customer_company'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SalesOrder',
            new_name='Order',
        ),
    ]
